#!/bin/bash
Run()
{
   #Run Program
   python3 /usr/local/bin/PyFiXL/main.py
}
Install()
{
   #Copy files to /usr/local/bin
   read -p "Please enter path of PyFiXL directory: " dirname
   cp -r "$dirname" /usr/local/bin
   echo "Operation 'Install' has finished. Use pyfixl -r to run the program."
}
Help()
{
   # Display Help
   echo
   echo "These commands will help you install and use PyFiXL."
   echo
   echo "Syntax: pyfixl [-h|r|i]"
   echo "options:"
   echo "h     Print this Help."
   echo "r     Start PyFiXL in CLI."
   echo "i     Install PyFiXL to usr/local/bin."
   echo
}

# Get the options
while getopts ":hri" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      r) # call Run
         Run
         exit;;
      i) # call Install
         Install
         exit;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done
